swagger: "2.0.21"
info:
  description: "This is an API documentation for organization managment service. \n  [Find out more about organization management service](https://parallel6.atlassian.net/wiki/spaces/PROV/pages/792068410/Organization+management+Service) \n [Find out more about Provenance](https://parallel6.atlassian.net/wiki/spaces/PROV/pages/687046714/Program+Provenance)"
  version: "1.0.0"
  title: "Organization Management"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "keyur.gandhi@harman.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: "Find out more about custom response code"
  url: "https://parallel6.atlassian.net/wiki/spaces/PROV/pages/779878453/Error+Codes+Draft"
  
host: "localhost:8080"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /organizations/type:
    get:
      tags:
      - "organization"
      summary: "Returns list of organization type"
      description: "Returns list of organization type with type id"
      operationId: "getOrgnaizationType"
      produces:
      - "application/json"
      parameters: []
      security:
      - Authorization: []      
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: '#/definitions/OrganizationType'
        400:
          description: "Bad Request"
          schema:
           $ref: "#/definitions/ErrorResponse"
        401:
          description: " Unauthorized Access"
          schema:
             type: "string"
             description: "Unauthorized Access"
        403:
          description: " Forbidden"
          schema:
             type: "string"
             description: "Forbidden"
        404:
          description: " URL not found"
          schema:
             type: "string"
             description: "URL not found"
        500:
          description: " Internal server error"
          schema:
             type: "string"
             description: "Internal server error"
        503:
          description: " Service is unavailable"
          schema:
             type: "string"
             description: "Service is unavailable"
  /organizations:
    post:
      tags:
      - "organization"
      summary: "Create an organization"
      description: ""
      operationId: "createOrganization"
      produces:
      - "application/json"
      security:
      - Authorization: []
      parameters:
      - in: "body"
        name: "body"
        description: "creates a new organization"
        required: true
        schema:
          $ref: "#/definitions/OrganizationRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/OrganizationResponse"
        400:
          description: "Bad Request"
          schema:
           $ref: "#/definitions/ErrorResponse"
        401:
          description: " Unauthorized Access"
          schema:
             type: "string"
             description: "Unauthorized Access"
        403:
          description: " Forbidden"
          schema:
             type: "string"
             description: "Forbidden"
        404:
          description: " URL not found"
          schema:
             type: "string"
             description: "URL not found"
        500:
          description: " Internal server error"
          schema:
             type: "string"
             description: "Internal server error"
        503:
          description: " Service is unavailable"
          schema:
             type: "string"
             description: "Service is unavailable"
  /organizations/{orgId}:
    put:
      tags:
      - "organization"
      summary: "Update an organization"
      description: ""
      operationId: "updateOrganization"
      produces:
      - "application/json"
      security:
      - Authorization: []      
      parameters:
      - name: "orgId"
        in: "path"
        description: "GUID of the organization"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated oranization object"
        required: true
        schema:
          $ref: "#/definitions/OrganizationRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/OrganizationResponse"
        400:
          description: "Bad Request"
          schema:
           $ref: "#/definitions/ErrorResponse"
        401:
          description: " Unauthorized Access"
          schema:
             type: "string"
             description: "Unauthorized Access"
        403:
          description: "Forbidden"
          schema:
             type: "string"
             description: "Forbidden"
        404:
          description: " URL not found"
          schema:
             type: "string"
             description: "URL not found"
        500:
          description: " Internal server error"
          schema:
             type: "string"
             description: "Internal server error"
        503:
          description: " Service is unavailable"
          schema:
             type: "string"
             description: "Service is unavailable"
    get:
      tags:
      - "organization"
      summary: "Find organization details by org ID"
      description: ""
      operationId: "getOrgById"
      produces:
      - "application/json"
      security:
      - Authorization: []      
      parameters:
      - name: "orgId"
        in: "path"
        description: "GUID of the organization that needs to be fetched"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/OrganizationResponse"
        400:
          description: "Bad Request"
          schema:
           $ref: "#/definitions/ErrorResponse"
        401:
          description: " Unauthorized Access"
          schema:
             type: "string"
             description: "Unauthorized Access"
        403:
          description: "Forbidden"
          schema:
             type: "string"
             description: "Forbidden"
        404:
          description: " URL not found"
          schema:
             type: "string"
             description: "URL not found"
        500:
          description: " Internal server error"
          schema:
             type: "string"
             description: "Internal server error"
        503:
          description: " Service is unavailable"
          schema:
             type: "string"
             description: "Service is unavailable"

securityDefinitions:
  Authorization:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  OrganizationRequest:
    type: "object"
    properties:
      name:
        type: "string"
        description: "name of the organization"
      organizationTypeId:
        type: "string"
        description: "Organization type GUID"
  OrganizationResponse:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Organization GUID"
      attributes:
        type: "object"
        properties:
          name:
            type: "string"
            description: "name of the organization"
      relationships:
        type: "object"
        properties:
          OrganizationType:
            $ref: "#/definitions/OrganizationType"
  OrganizationType:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Organization type GUID"
      attributes:
        type: "object"
        properties:
          name:
            type: "string"
            description: "name of organization type"
  ErrorResponse:
   type: "object"
   properties:
      errors:
        type: "array"
        items: 
          properties:
            code:
              type: "string"
              description: "code for error"
            source:
              type: "string"
              description: "source of error"
            title:
              type: "string"
              description: "type of error"
            detail:
              type: "string"
              description: "details of error"


      
   

